name: Matrix Demo
on: 
  push:
     branch:
        Dev
jobs: 
   build:
      strategy: 
         matrix:
            operating-system: [ubuntu-latest, windows-latest]
      runs-on:  ${{strategy.matrix.operating-system}}
      steps: 
       -  name: Get code
          uses: actions/checkout@v3
       -  name: setup JDK
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: '21'
       