name: Output pull  workflow
on:
  pull_request:
    types: opened
  workflow_dispatch:  
jobs:
  issue_info_job:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue trigger
        run: echo "${{toJson(github)}}"