name: Test build and deploy workflow
on: push
jobs:
  build_and_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean install
      - name: Test
        run: mvn test
  deploy_job:
    needs: build_and_test_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying..."