name: Test build and deploy workflow
on: push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
        
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Build with Maven
        run: mvn clean install
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
         name: target-files-uploaded
         path: target/

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests with Maven
        run: mvn test

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Get Artifcat
        uses: actions/download-artifact@v4
        with:
          name: target-file-uploaded
      - name: Output
        run: ls  
      - name: Deploying (placeholder)
        run: echo "Deploying..."